### ISSUE TITLE
EPA-ng step fails

### ISSUE THREAD

**Issue by Tamtatatam** [hariszaf/darn#3]
Hi 
I tried to run the pipeline, but step 2 seems to fail and I can't figure out how to solve this problem. The output files are written into the defined directory, so I think this is not the issue, but maybe DARN can't find epa-ng? Any idea on how to solve this? Thanks a lot in advance!

Here the log:
 
>>> STEP 2: placement of the input reads on the reference COI phylogenetic tree of DARN, 
 using the EPA-ng algorithm (Barbera et al. 2018). 
INFO Selected: Output dir: ./
INFO Selected: Query file: query.fasta
INFO Selected: Tree file: /home/docs/magicTree.bestTree
INFO Selected: Reference MSA: /home/docs/magic_tree_aln.fasta
INFO Selected: Automatic switching of use of per rate scalers
INFO Selected: Preserving the root of the input tree
INFO Selected: Specified model: GTR+F+R10
INFO     ______ ____   ___           _   __ ______
        / ____// __ \ /   |         / | / // ____/
       / __/  / /_/ // /| | ______ /  |/ // / __  
      / /___ / ____// ___ |/_____// /|  // /_/ /  
     /_____//_/    /_/  |_|      /_/ |_/ \____/ (v0.3.8)
./darn.sh: line 158:    39 Killed                  /home/tools/epa/bin/epa-ng -t /home/docs/magicTree.bestTree -s /home/docs/magic_tree_aln.fasta -m GTR+F+R10 -q query.fasta

 <<< STEP 2 has been completed. 

 >>> STEP 3: Build assignment profiles per input query, 
 using the examine assign of the gappa package (Czech et al. 2020). 
--jplace-path: Path does not exist: epa_result.jplace
Run with --help for more information.
--jplace-path: Path does not exist: epa_result.jplace
Run with --help for more information.

After this the pipeline continues with steps 4, 5 and 6, but as DARN does not find the relevant files/data, it does not produce the right output.

**Comment by hariszaf** [comment]
Hi @Tamtatatam !

Thanks to containers `darn`  comes with everything needed, meaning `epa-ng` is already there and `darn` knows 
where to find it. 

It is my belief that the previous step has not been completed the right way. 

Would you like to try running `darn` with the [`marine_part.fasta`](https://github.com/hariszaf/darn/tree/main/analysis) file? 
If everything goes well, then it is probably a format issue of your input file. 

If something goes bad, could you send me the error so we can solve this ? 

Many thanks for the feedback!

**Comment by Tamtatatam** [comment]
Thanks for the quick reply. I tested it with a few datasets and subsets now and indeed, some subsets of the original dataset that caused the crash work well, while others do not and result in the same error. Not sure yet which sequences are problematic, I will look into that.

**Comment by hariszaf** [comment]
Thanks a lot for your interest in `darn` @Tamtatatam 

If you figure this out please let me know so maybe i ll find a way to convert bad formats 
to valid ones. 

If you have any ideas for futher modules `darn` would be nice to support, 
feel free to open a [discussion](https://github.com/hariszaf/darn/discussions)! :100:

**Comment by hariszaf** [comment]
@Tamtatatam  i will now close this issue. 
For antything might be needed, feel free to reopen it! 
Best!
